//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('posts')
export class postsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  text: string;

  @Column('text', { nullable: true })
  audio: string;

  @Column('text', { nullable: true })
  video: string;

  @Column('text', { nullable: true })
  link: string;

  @Column('text', { nullable: true })
  photo: string;
}
