//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const videosTitle = () => {
  const record = useRecordContext();
  return <span>videos {record ? `"${record.postId}"` : ''}</span>;
};

export const videosList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="postId" reference="posts" />
      <ReferenceField source="chatId" reference="messages" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const videosEdit = () => (
  <Edit title={<videosTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="postId" reference="posts" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="chatId" reference="messages" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const videosCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="postId" reference="posts" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="chatId" reference="messages" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput source="postId" label="postId" reference="posts" alwaysOn />,
  <ReferenceInput
    source="chatId"
    label="chatId"
    reference="messages"
    alwaysOn
  />,
];
