//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    users: {
      name: 'Users',
      fields: {
        name: 'Name',
        lastname: 'Lastname',
        email: 'Email',
        password: 'Password',
        id: 'id',
      },
    },
    posts: {
      name: 'Posts',
      fields: {
        text: 'Text',
        audio: 'Audio',
        video: 'Video',
        link: 'Link',
        photo: 'Photo',
        id: 'id',
      },
    },
    messages: {
      name: 'Messages',
      fields: { text: 'Text', image: 'Image', video: 'Video', id: 'id' },
    },
    friends: {
      name: 'Friends',
      fields: { userId1: 'User Id1', userId2: 'User Id2', id: 'id' },
    },
    photos: { name: 'Photos', fields: { postId: 'Post Id', id: 'id' } },
    videos: {
      name: 'Videos',
      fields: { postId: 'Post Id', chatId: 'Chat Id', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        lastname: 'Lastname (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        id: 'id',
      },
    },
    posts: {
      name: 'Posts (fr)',
      fields: {
        text: 'Text (fr)',
        audio: 'Audio (fr)',
        video: 'Video (fr)',
        link: 'Link (fr)',
        photo: 'Photo (fr)',
        id: 'id',
      },
    },
    messages: {
      name: 'Messages (fr)',
      fields: {
        text: 'Text (fr)',
        image: 'Image (fr)',
        video: 'Video (fr)',
        id: 'id',
      },
    },
    friends: {
      name: 'Friends (fr)',
      fields: { userId1: 'User Id1 (fr)', userId2: 'User Id2 (fr)', id: 'id' },
    },
    photos: {
      name: 'Photos (fr)',
      fields: { postId: 'Post Id (fr)', id: 'id' },
    },
    videos: {
      name: 'Videos (fr)',
      fields: { postId: 'Post Id (fr)', chatId: 'Chat Id (fr)', id: 'id' },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
